In [42]:
from google.colab import drive
drive.mount("/content/drive",force_remount="TRUE")

Mounted at /content/drive


In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [44]:
tf.__version__

'2.4.0'

#Importing Dataset

In [45]:
df = pd.read_excel("/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)-20200808T101226Z-001/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Artificial_Neural_Network for Regression/Final Folder/Dataset/Folds5x2_pp.xlsx")

In [46]:
x= df.iloc[:,:-1].values
y= df.iloc[:,-1].values
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


#Data Preprocessing

Splitting the training set and test set

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0) 

#Creating the ANN model

Initialization of the ANN model 

In [48]:
ann = tf.keras.models.Sequential()

Creating the 1st input layer

In [49]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Creating the 2nd Input layer

In [50]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Creating the output layer

In [51]:
ann.add(tf.keras.layers.Dense(units=1))

#Training the ANN model

Compiling the model

In [52]:
ann.compile(optimizer="adam",loss= "mean_squared_error")

Training the model

In [53]:
ann.fit(x_train,y_train,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 960us/step - loss: 44956.1995
Epoch 2/100
240/240 [==============================] - 0s 952us/step - loss: 165.5166
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 148.4726
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 138.7052
Epoch 5/100
240/240 [==============================] - 0s 984us/step - loss: 122.1351
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 105.8600
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 92.3577
Epoch 8/100
240/240 [==============================] - 0s 993us/step - loss: 77.4591
Epoch 9/100
240/240 [==============================] - 0s 992us/step - loss: 65.6041
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 54.2798
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 47.6443
Epoch 12/100
240/240 [==============================] - 0s 983us/st

#Predicting Results

In [54]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[431.41 431.23]
 [462.36 460.01]
 [465.83 461.14]
 ...
 [473.09 473.26]
 [439.84 438.  ]
 [459.06 463.28]]


Calculating R2 score

In [55]:
from sklearn.metrics import r2_score
acc_ann = r2_score(y_pred,y_test)
print(acc_ann)

0.9107937714692215
